/**
 * Generates the base-map geometry used by every map on the site.
 *
 * Source: Natural Earth (public domain) via the `world-atlas` package.
 * Output: data/generated/basemap.ts — projected SVG path strings plus the
 * projection parameters, so the browser never has to download TopoJSON.
 *
 * Run with: npm run generate:map
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { geoConicConformal, geoPath, geoGraticule } from 'd3-geo';
import { feature } from 'topojson-client';
import { presimplify, simplify } from 'topojson-simplify';

const require = createRequire(import.meta.url);
const WIDTH = 1000;
const FIT = {
  type: 'MultiPoint',
  coordinates: [
    [-6, 11], [56, 11], [-6, 50], [56, 50], [25, 51], [25, 11], [10, 50], [40, 50],
  ],
};

const projection = geoConicConformal().parallels([30, 45]).rotate([-25, 0]);
projection.fitWidth(WIDTH, FIT);
const bounds = geoPath(projection).bounds(FIT);
const HEIGHT = Math.ceil(bounds[1][1] - bounds[0][1]);
projection.fitSize([WIDTH, HEIGHT], FIT);

const pad = 60;
projection.clipExtent([[-pad, -pad], [WIDTH + pad, HEIGHT + pad]]);

const round = (d) => d.replace(/(\d+\.\d)\d+/g, '$1');

function landPath(file, minWeight) {
  const topo = JSON.parse(readFileSync(require.resolve(`world-atlas/${file}`), 'utf8'));
  const simplified = simplify(presimplify(topo), minWeight);
  const land = feature(simplified, simplified.objects.land);
  return round(geoPath(projection)(land));
}

const land = landPath('land-50m.json', 0.0004);
const graticule = round(geoPath(projection)(geoGraticule().step([5, 5]).extent([[-20, 5], [70, 60]])()));

const out = `// AUTO-GENERATED by scripts/build-land.mjs — do not edit by hand.
// Land geometry: Natural Earth 1:50m (public domain) via the world-atlas package.

export const MAP_WIDTH = ${WIDTH};
export const MAP_HEIGHT = ${HEIGHT};
export const PROJECTION = {
  parallels: [30, 45] as [number, number],
  rotate: [-25, 0] as [number, number],
  scale: ${projection.scale()},
  translate: [${projection.translate().join(', ')}] as [number, number],
};

export const LAND_PATH = ${JSON.stringify(land)};

export const GRATICULE_PATH = ${JSON.stringify(graticule)};
`;
writeFileSync(new URL('../data/generated/basemap.ts', import.meta.url), out);
console.log(`basemap.ts written: ${WIDTH}x${HEIGHT}, land ${(land.length / 1024).toFixed(1)} KB`);
